package pssm;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertTrue;

import java.util.LinkedList;
import java.util.List;

import org.testng.annotations.Test;

public class LibraryTest {
    @Test
    public void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");

        List<Integer> list = new LinkedList<>();
        list.add(0);
        list.add(1);
        assertEquals(list.get(0), 0);
        assertEquals(list.get(1), 1);
        assertEquals(list.remove(0), 0);
        assertEquals(list.get(0), 1);
    }
}
